name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Install dependencies
      run: dotnet restore OrderManagement.Api/OrderManagement.Api.csproj

    - name: Build
      run: dotnet build OrderManagement.Api/OrderManagement.Api.csproj --configuration Release

    - name: Test
      run: dotnet test OrderManagement.Tests/OrderManagement.Tests.csproj --configuration Release
